credentials:
  hmd:
    user: ''
    pswd: ''
  earthdata:
    user: ''
    pswd: ''
skeleton:
  year:
    min: 2000
    max: 2021
  week:
    min: 1
    max: 52
  age: {'[0,15)': 0, '[15,65)': 15, '[65,75)': 65, '[75,85)': 75, '85+': 85}
  age_width: {'[0,15)': 15, '[15,65)': 50, '[65,75)': 10, '[75,85)': 10, '85+': Inf}
  sex: {Male: 'Male', Female: 'Female'}
  region: [
    'AT',
    'AU',
    'BE',
    'BG',
    'CA',
    'CH',
    'CL',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GB-EAW',
    'GB-NIR',
    'GB-SCT',
    'GR',
    'HR',
    'HU',
    'IL',
    'IS',
    'IT',
    'KR',
    'LT',
    'LU',
    'LV',
    'NL',
    'NO',
    'NZ',
    'PL',
    'PT',
    'RU',
    'SE',
    'SI',
    'SK',
    'TW',
    'US'
]
